apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: nginx-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "nginx:1.8"
          name: nginx
          ports: 
            - 
              containerPort: 80
          volumeMounts: 
            - 
              mountPath: /usr/share/nginx/html
              name: nginx-vol
      volumes: 
        - 
          emptyDir: {}
          name: nginx-vol
