kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-provisioner-rabc
subjects:
- kind: ServiceAccount
  name: rbd-provision
  namespace: default
roleRef:
  kind: ClusterRole
  #name: system:controller:persistent-volume-binder
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbd-provisioner
