apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-dynamic
provisioner: ceph.com/rbd
parameters:
  monitors: ceph-monitoring.default.svc.cluster.local.:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: ceph-dynamic
  userId: admin
  userSecretName: ceph-secret
  userSecretNamespace: default
  imageFormat: "2"
  imageFeatures: "layering"