apiVersion: v1
kind: Pod
metadata:
  name: ceph-test-pod
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    volumeMounts:
    - name: nginxpath
      mountPath: /usr/share/nginx/html
  volumes:
    - name: nginxpath
      persistentVolumeClaim:
        claimName: ceph-dynamic

