apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-dynamic
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-dynamic
  resources:
    requests:
      storage:20M