apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-dynamic
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Mi
  storageClassName: ceph-dynamic