apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-dynamic
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.188.16:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: ceph-dynamic
  userId: admin
  userSecretName: ceph-secret
  userSecretNamespace: default
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
